- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Download Zabbix DEB
      get_url:
        url: https://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.4-1+xenial_all.deb
        dest: /home/ubuntu/zabbix-release_4.4-1+xenial_all.deb
    - name: Install Zabbix repository
      apt:
        deb: /home/ubuntu/zabbix-release_4.4-1+xenial_all.deb
    - name: Install zabbix-agent
      apt: 
        name: zabbix-agent
        state: present
        update_cache: true
    - name: Configure /etc/zabbix/zabbix_agentd.conf
      copy:
        src: ../zabbix-agent/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: '0644'
        force: yes
    - name: Open zabbix-agent port 
      ufw:
        rule: allow
        port: '10050'
    - name: Enable zabbix-agent service
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes