- hosts: monitor
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install MySQL Server
      apt: 
        name: mysql-server
        state: present
        update_cache: true
    - name: Install NMAP
      apt: 
        name: nmap
        state: present
        update_cache: true
    - name: Install Traceroute
      apt: 
        name: traceroute
        state: present
        update_cache: true
    - name: Install PyMySQL
      apt: 
        name: 
        - python3-pymysql
        - python-pymysql
        - python-apt
        - python3-apt
        state: latest
        update_cache: true
    - name: Install NGINX
      apt: 
        name: nginx
        state: present
        update_cache: true
    - name: Download Zabbix DEB
      get_url:
        url: https://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.4-1+xenial_all.deb
        dest: /home/ubuntu/zabbix-release_4.4-1+xenial_all.deb
    - name: Install Zabbix repository
      apt:
        deb: /home/ubuntu/zabbix-release_4.4-1+xenial_all.deb
    - name: Install zabbix-server-mysql
      apt: 
        name: zabbix-server-mysql
        state: present
        update_cache: true
    - name: Install zabbix-frontend-php
      apt: 
        name: zabbix-frontend-php
        state: present
        update_cache: true
    - name: Install zabbix-nginx-conf
      apt: 
        name: zabbix-nginx-conf
        state: present
        update_cache: true
    - name: Install zabbix-agent
      apt: 
        name: zabbix-agent
        state: present
        update_cache: true
    - name: Create zabbix DB
      mysql_db:
        name: zabbix
        state: present
        config_file: /etc/mysql/debian.cnf
        encoding: utf8
        collation: utf8_bin
    - name: Create DB user zabbix
      mysql_user:
        name: zabbix
        config_file: /etc/mysql/debian.cnf
        password: zbixpwd
        priv: 'zabbix.*:ALL'
        state: present
    - name: Configure /etc/zabbix/nginx.conf
      copy:
        src: ../zabbix-server/nginx.conf
        dest: /etc/zabbix/nginx.conf
        owner: root
        group: root
        mode: '0644'
        force: yes
    - name: Configure /etc/zabbix/php-fpm.conf
      copy:
        src: ../zabbix-server/php-fpm.conf
        dest: /etc/zabbix/php-fpm.conf
        owner: root
        group: root
        mode: '0644'
        force: yes
    - name: Importing zabbix data
      shell: zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -uzabbix -pzbixpwd zabbix
    - name: Enable zabbix-server service
      service:
        name: zabbix-server
        state: restarted
        enabled: yes
    - name: Enable zabbix-agent service
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes
    - name: Enable NGINX service
      service:
        name: nginx
        state: restarted
        enabled: yes
    - name: Enable php7.0-fpm service
      service:
        name: php7.0-fpm
        state: restarted
        enabled: yes